// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Manual sidebar configuration with modules organized as a category
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'intro', // Introduction page
        'research-articles', // Research articles as the first item under the category
        {
          type: 'category',
          label: 'Core Modules',
          items: [
            'modules', // Overview page
            {
              type: 'category',
              label: 'Detailed Modules',
              items: [
                'modules/module-1-ros2',
                'modules/module-2-digital-twin',
                'modules/module-3-ai-robot-brain',
                'modules/module-4-vla'
              ]
            }
          ]
        },
        {type: 'autogenerated', dirName: 'physical-ai-humanoid-robotics'}
      ],
    },
  ],
};

export default sidebars;
